### ISSUE TITLE
Error "Error encountered while running bot: 'pixels'"

### ISSUE THREAD

**Issue by Meppci** [Geosearchef/placebot#13]
Bot takes 2 images of board, then "refreshes target config" and then it says "Error encountered while running bot: 'pixels'", program crashes.
Python says that error is "KeyError", line 77 in placebot.py

**Comment by Geosearchef** [comment]
What is your target configuration file?

**Comment by Meppci** [comment]
If you mean config.json here it is: 
```
{
    "accounts": [
        {"username": " my username here", "password":  "my pass here"}
    ],
    "target_configuration_url": "C:\\Users\\Govnoed\\Desktop\\placebot\\src\\config.json"
}
```
I tried adding 10 accounts but that still doesnt work :(

**Comment by Meppci** [comment]
ok im idiot, i had to place path to out.cfg in "target_configuration_url", not path to config. everything works
